language: node_js
node_js:
  - "6.11.1"
  - "8.1.4"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8


install:
  - npm install
  - npm install typescript -g

before_script:
  - npm run dist
