language: node_js
node_js:
  - "4.2"
  - "5.1"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8


install:
  - npm install
  - npm install typescript -g
  - npm install tsd -g
  - tsd install

before_script:
  - npm run dist
